/*
-- Query: SELECT * FROM livestockweb.health_conditions
LIMIT 0, 1000

-- Date: 2021-06-10 15:21
*/
INSERT INTO `livestockweb`.`health_conditions` (`id`,`name`,`local_term`,`organ_system_id`,`common_in_region`,`description`,`how_to_diganose`,`treatment`,`advice_to_farmer`,`preventive_measure`,`quick_action`,`created_at`,`updated_at`) VALUES (1,'Brucellosis','B local',1,NULL,'Bovine brucellosis is a highly transferable bacterial disease. It is mainly caused by Brucella abortus, causing late term-abortion and infertility in cattle. The disease is also a serious zoonosis (disease shared by animals and human), causing on-and-off fever in humans. Main natural hosts are cattle, horses and humans. The bacteria is excreted in uterine discharges and in milk. Diagnosis depends on the isolation of Brucella sp. from abortion material, udder secretions or from tissues removed at post-mortem. Brucella abortus, B. melitensis and B. suis are highly pathogenic for humans.','History of abortion between 2nd and 3rd trimester (5th and 9th month) of pregnancy, orchitis/epididymitis in bulls, infertility, hygromas on leg joints, retained placenta, arthritis','No practical treatment available, cull and slaughter infected animal','Isolate suspect animal, disinfect surroundings, do not touch vaginal secretions, discard contaminated milk','Isolate new animals before introducing to the herd, regular screening test for Brucellosis',1,NULL,NULL);
INSERT INTO `livestockweb`.`health_conditions` (`id`,`name`,`local_term`,`organ_system_id`,`common_in_region`,`description`,`how_to_diganose`,`treatment`,`advice_to_farmer`,`preventive_measure`,`quick_action`,`created_at`,`updated_at`) VALUES (2,'Metritis','Pamamaga ng matris',1,NULL,'Metritis, an inflammation of the uterus, is caused by bacterial infection, and usually is seen following calving. It occurs most commonly after calvings complicated by dystocia, retained fetal membranes, twins or stillbirths.','Foul-fetid vulvar discharge, red-brown fetid uterine discharge, history, elimination of common diseases, rectal palpation reveals enlargement and thickened doughy feel of uterine horns','Administration of prstaglandin F2-α, Intrauterine antibiotic infusion and vitamins administration','Clean drinking water must be readily available, ensure adequate mineral (calcium) and vitamin supplementation; provide dry and clean maternity environment; hygienic calving measures, avoid overconditioned cows at calving','Ensure adequate mineral (calcium) and vitamin supplementation; provide dry and clean maternity environment; hygienic calving measures, avoid overconditioned cows at calving',1,NULL,NULL);
INSERT INTO `livestockweb`.`health_conditions` (`id`,`name`,`local_term`,`organ_system_id`,`common_in_region`,`description`,`how_to_diganose`,`treatment`,`advice_to_farmer`,`preventive_measure`,`quick_action`,`created_at`,`updated_at`) VALUES (3,'Bloat','Kabag',2,NULL,'Bloat is an overdistention of the rumen with the gases of fermentation in the form of a persistent foam mixed with the ruminal contents, called primary or frothy bloat, or in the form of free gas separated from the ingesta, called secondary or free-gas bloat.','Commonly occurs in grazing animals, rapid distension of left flank, animal not ruminating, pasty diarrhea. Distress','Remove animal from pasture area immediately, drenching/use stomach tube with anti-foaming agent such as vegetable oil, use trocar and cannula, emergency rumenotomy','Remove animal from pasture area immediately','Provide good quality roughage and concentrates, minimize grazing in legume-rich pasture areas, avoid overfeeding finely ground grains',1,NULL,NULL);
